<a href="https://colab.research.google.com/github/Pooveannan/Python-Projects/blob/main/Numpy_Chess_Dataset.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from google.colab import files
uploaded = files.upload()

TypeError: 'NoneType' object is not subscriptable

In [1]:
from google.colab import drive
drive.mount('/content/gdrive')

Mounted at /content/gdrive

In [3]:

import pandas as pd
df=pd.read_csv('gdrive/My Drive/chess_game_dataset.csv')
df

,id,rated,created_at,last_move_at,turns,victory_status,winner,increment_code,white_id,white_rating,black_id,black_rating,moves,opening_eco,opening_name,opening_ply
0,TZJHLljE,False,1.504210e+12,1.504210e+12,13.0,outoftime,white,15+2,NaN,NaN,a-00,1191.0,NaN,D10,Slav Defense: Exchange Variation,5.0
1,NaN,True,NaN,NaN,16.0,resign,black,5+10,NaN,1322.0,skinnerua,1261.0,NaN,B00,Nimzowitsch Defense: Kennedy Variation,4.0
2,mIICvQHh,True,1.504130e+12,1.504130e+12,NaN,mate,white,5+10,ischia,NaN,a-00,1500.0,e4 e5 d3 d6 Be3 c6 Be2 b5 Nd2 a5 a4 c5 axb5 Nc...,NaN,NaN,3.0
3,NaN,NaN,1.504110e+12,1.504110e+12,61.0,mate,white,20+0,daniamurashov,NaN,adivanov2009,NaN,d4 d5 Nf3 Bf5 Nc3 Nf6 Bf4 Ng4 e3 Nc6 Be2 Qd7 O...,NaN,Queen's Pawn Game: Zukertort Variation,3.0
4,9tXo1AUZ,True,1.504030e+12,1.504030e+12,95.0,mate,white,30+3,nik221107,1523.0,NaN,1469.0,e4 e5 Nf3 d6 d4 Nc6 d5 Nb4 a3 Na6 Nc3 Be7 b4 N...,C41,Philidor Defense,5.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20053,EfqH7VVH,True,NaN,1.499791e+12,NaN,resign,white,NaN,belcolt,1691.0,jamboger,1220.0,d4 f5 e3 e6 Nf3 Nf6 Nc3 b6 Be2 Bb7 O-O Be7 Ne5...,A80,NaN,2.0
20054,WSJDhbPl,True,1.499698e+12,1.499699e+12,NaN,mate,black,10+0,NaN,1233.0,farrukhasomiddinov,1196.0,d4 d6 Bf4 e5 Bg3 Nf6 e3 exd4 exd4 d5 c3 Bd6 Bd...,A41,NaN,2.0
20055,yrAas0Kj,True,1.499698e+12,1.499698e+12,NaN,NaN,white,10+0,jamboger,1219.0,schaaksmurf3,1286.0,d4 d5 Bf4 Nc6 e3 Nf6 c3 e6 Nf3 Be7 Bd3 O-O Nbd...,D00,Queen's Pawn Game: Mason Attack,3.0
20056,b0v4tRyF,NaN,1.499696e+12,1.499697e+12,NaN,resign,white,10+0,marcodisogno,1360.0,jamboger,1227.0,e4 d6 d4 Nf6 e5 dxe5 dxe5 Qxd1+ Kxd1 Nd5 c4 Nb...,NaN,NaN,NaN
20057,N8G2JHGG,True,1.499643e+12,1.499644e+12,78.0,mate,NaN,10+0,jamboger,1235.0,ffbob,1339.0,d4 d5 Bf4 Na6 e3 e6 c3 Nf6 Nf3 Bd7 Nbd2 b5 Bd3...,D00,Queen's Pawn Game: Mason Attack,NaN

In [4]:
df.isnull().sum()

id                3639
rated             3611
created_at        3558
last_move_at      3558
turns             3636
victory_status    3567
winner            3694
increment_code    3631
white_id          3646
white_rating      3713
black_id          3650
black_rating      3614
moves             3713
opening_eco       3736
opening_name      3651
opening_ply       3619
dtype: int64

In [5]:
#total rows
len(df)

20058

In [6]:
(df.isna().sum()/len(df))*100

id                18.142387
rated             18.002792
created_at        17.738558
last_move_at      17.738558
turns             18.127430
victory_status    17.783428
winner            18.416592
increment_code    18.102503
white_id          18.177286
white_rating      18.511317
black_id          18.197228
black_rating      18.017749
moves             18.511317
opening_eco       18.625985
opening_name      18.202214
opening_ply       18.042676
dtype: float64

In [7]:
### 3)
num_col = df.select_dtypes(include= "float64").columns
for col in num_col:
 df[col]=df[col].fillna(df[col].median())
df

,id,rated,created_at,last_move_at,turns,victory_status,winner,increment_code,white_id,white_rating,black_id,black_rating,moves,opening_eco,opening_name,opening_ply
0,TZJHLljE,False,1.504210e+12,1.504210e+12,13.0,outoftime,white,15+2,NaN,1567.0,a-00,1191.0,NaN,D10,Slav Defense: Exchange Variation,5.0
1,NaN,True,1.496083e+12,1.496125e+12,16.0,resign,black,5+10,NaN,1322.0,skinnerua,1261.0,NaN,B00,Nimzowitsch Defense: Kennedy Variation,4.0
2,mIICvQHh,True,1.504130e+12,1.504130e+12,55.0,mate,white,5+10,ischia,1567.0,a-00,1500.0,e4 e5 d3 d6 Be3 c6 Be2 b5 Nd2 a5 a4 c5 axb5 Nc...,NaN,NaN,3.0
3,NaN,NaN,1.504110e+12,1.504110e+12,61.0,mate,white,20+0,daniamurashov,1567.0,adivanov2009,1562.5,d4 d5 Nf3 Bf5 Nc3 Nf6 Bf4 Ng4 e3 Nc6 Be2 Qd7 O...,NaN,Queen's Pawn Game: Zukertort Variation,3.0
4,9tXo1AUZ,True,1.504030e+12,1.504030e+12,95.0,mate,white,30+3,nik221107,1523.0,NaN,1469.0,e4 e5 Nf3 d6 d4 Nc6 d5 Nb4 a3 Na6 Nc3 Be7 b4 N...,C41,Philidor Defense,5.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20053,EfqH7VVH,True,1.496083e+12,1.499791e+12,55.0,resign,white,NaN,belcolt,1691.0,jamboger,1220.0,d4 f5 e3 e6 Nf3 Nf6 Nc3 b6 Be2 Bb7 O-O Be7 Ne5...,A80,NaN,2.0
20054,WSJDhbPl,True,1.499698e+12,1.499699e+12,55.0,mate,black,10+0,NaN,1233.0,farrukhasomiddinov,1196.0,d4 d6 Bf4 e5 Bg3 Nf6 e3 exd4 exd4 d5 c3 Bd6 Bd...,A41,NaN,2.0
20055,yrAas0Kj,True,1.499698e+12,1.499698e+12,55.0,NaN,white,10+0,jamboger,1219.0,schaaksmurf3,1286.0,d4 d5 Bf4 Nc6 e3 Nf6 c3 e6 Nf3 Be7 Bd3 O-O Nbd...,D00,Queen's Pawn Game: Mason Attack,3.0
20056,b0v4tRyF,NaN,1.499696e+12,1.499697e+12,55.0,resign,white,10+0,marcodisogno,1360.0,jamboger,1227.0,e4 d6 d4 Nf6 e5 dxe5 dxe5 Qxd1+ Kxd1 Nd5 c4 Nb...,NaN,NaN,4.0
20057,N8G2JHGG,True,1.499643e+12,1.499644e+12,78.0,mate,NaN,10+0,jamboger,1235.0,ffbob,1339.0,d4 d5 Bf4 Na6 e3 e6 c3 Nf6 Nf3 Bd7 Nbd2 b5 Bd3...,D00,Queen's Pawn Game: Mason Attack,4.0

In [ ]:
## 4) I) checking invalid ratings
import numpy as np
df.loc[(df['white_rating']<=0)|(df['white_rating']>2500),'white_rating']=np.nan
df.isna().sum()

id                3639
rated             3611
created_at           0
last_move_at         0
turns                0
victory_status    3567
winner            3694
increment_code    3631
white_id          3646
white_rating        30
black_id          3650
black_rating         0
moves             3713
opening_eco       3736
opening_name      3651
opening_ply          0
dtype: int64

In [ ]:
### Results and Winner Standardization

df["winner"].value_counts()

winner
white    8182
black    7397
draw      785
Name: count, dtype: int64

In [8]:
df['winner']=df['winner'].str.lower()
df

,id,rated,created_at,last_move_at,turns,victory_status,winner,increment_code,white_id,white_rating,black_id,black_rating,moves,opening_eco,opening_name,opening_ply
0,TZJHLljE,False,1.504210e+12,1.504210e+12,13.0,outoftime,white,15+2,NaN,1567.0,a-00,1191.0,NaN,D10,Slav Defense: Exchange Variation,5.0
1,NaN,True,1.496083e+12,1.496125e+12,16.0,resign,black,5+10,NaN,1322.0,skinnerua,1261.0,NaN,B00,Nimzowitsch Defense: Kennedy Variation,4.0
2,mIICvQHh,True,1.504130e+12,1.504130e+12,55.0,mate,white,5+10,ischia,1567.0,a-00,1500.0,e4 e5 d3 d6 Be3 c6 Be2 b5 Nd2 a5 a4 c5 axb5 Nc...,NaN,NaN,3.0
3,NaN,NaN,1.504110e+12,1.504110e+12,61.0,mate,white,20+0,daniamurashov,1567.0,adivanov2009,1562.5,d4 d5 Nf3 Bf5 Nc3 Nf6 Bf4 Ng4 e3 Nc6 Be2 Qd7 O...,NaN,Queen's Pawn Game: Zukertort Variation,3.0
4,9tXo1AUZ,True,1.504030e+12,1.504030e+12,95.0,mate,white,30+3,nik221107,1523.0,NaN,1469.0,e4 e5 Nf3 d6 d4 Nc6 d5 Nb4 a3 Na6 Nc3 Be7 b4 N...,C41,Philidor Defense,5.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20053,EfqH7VVH,True,1.496083e+12,1.499791e+12,55.0,resign,white,NaN,belcolt,1691.0,jamboger,1220.0,d4 f5 e3 e6 Nf3 Nf6 Nc3 b6 Be2 Bb7 O-O Be7 Ne5...,A80,NaN,2.0
20054,WSJDhbPl,True,1.499698e+12,1.499699e+12,55.0,mate,black,10+0,NaN,1233.0,farrukhasomiddinov,1196.0,d4 d6 Bf4 e5 Bg3 Nf6 e3 exd4 exd4 d5 c3 Bd6 Bd...,A41,NaN,2.0
20055,yrAas0Kj,True,1.499698e+12,1.499698e+12,55.0,NaN,white,10+0,jamboger,1219.0,schaaksmurf3,1286.0,d4 d5 Bf4 Nc6 e3 Nf6 c3 e6 Nf3 Be7 Bd3 O-O Nbd...,D00,Queen's Pawn Game: Mason Attack,3.0
20056,b0v4tRyF,NaN,1.499696e+12,1.499697e+12,55.0,resign,white,10+0,marcodisogno,1360.0,jamboger,1227.0,e4 d6 d4 Nf6 e5 dxe5 dxe5 Qxd1+ Kxd1 Nd5 c4 Nb...,NaN,NaN,4.0
20057,N8G2JHGG,True,1.499643e+12,1.499644e+12,78.0,mate,NaN,10+0,jamboger,1235.0,ffbob,1339.0,d4 d5 Bf4 Na6 e3 e6 c3 Nf6 Nf3 Bd7 Nbd2 b5 Bd3...,D00,Queen's Pawn Game: Mason Attack,4.0